### PR TITLE
Fix plot recipe for FODESystemSolution

### PR DESCRIPTION
**Pull request by ErikQQY**
I investigated the plot recipe today, and make our own recipe for ```FODESystemSolutoin```, I think it's working very well, let's take fractional order Chua system as an example here:

```julia
using FractionalDiffEq, Plots
function chua!(du, x, p, t)
    a, b, c, m0, m1 = p
    du[1] = a*(x[2]-x[1]-(m1*x[1]+0.5*(m0-m1)*(abs(x[1]+1)-abs(x[1]-1))))
    du[2] = x[1]-x[2]+x[3]
    du[3] = -b*x[2]-c*x[3]
end
α = [0.93, 0.99, 0.92]
x0 = [0.2; -0.1; 0.1]
h = 0.001; tspan = (0, 50)
p = [10.725, 10.593, 0.268, -1.1726, -0.7872]
prob = FODESystem(chua!, α, x0, tspan, p)
sol = solve(prob, h, NonLinearAlg())

p=plot(sol);
p01=plot(sol, vars=(0, 1));
p02=plot(sol, vars=(0, 2));
p012=plot(sol, vars=(0, 1, 2));
p12=plot(sol, vars=(1, 2));
p23=plot(sol, vars=(2, 3));
p13=plot(sol, vars=(1, 3));
p123=plot(sol, vars=(1, 2, 3));
plot(p, p01, p02, p012, p12, p23, p13, p123, layout=8)
```

newchua

@jClugstor Please review this when you are available😉

### CODE REVIEW

**Comment by ErikQQY** [comment]
If the plot recipe for ```FODESystemSolution``` is OK, we can use the similar recipe for ```FDDESystemSolution```, ```FractionalDifferenceSolution``` and ```FFODESystemSolution```, then all the plot issues are fixed🎉

**Comment by ErikQQY** [comment]
I think this PR plot recipe is ready to get merged. Coming PRs for ```FDDESystemSolution``` 🚀🚀

**Comment by jClugstor** [comment]
Sorry, I've been moving the last couple of days. The plot recipe looks awesome!

**Comment by ErikQQY** [comment]
Hahaha, that’s OK, take care.😉 Next we will add more details for our recipes, axis labels, legends, or whatever comes to mind!

**Pull request merged**
